mkdir "forge_1_19_3/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_19_2/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_19_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_18_2/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_17_1/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_16_5/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_15_2/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_14_4/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_12_2/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_12_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_8_8/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_8_8/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "forge_1_7_10/src/main/java/coloryr/allmusic_client"
mkdir "forge_1_7_10/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_14_4/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_15_2/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_16_5/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_17_1/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_18_2/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_19/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_19/src/main/resources/coloryr/allmusic_client/player/decoder"
mkdir "fabric_1_19_3/src/main/java/coloryr/allmusic_client"
mkdir "fabric_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder"

mklink /j "forge_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_19_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_12_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_8_8/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "forge_1_7_10/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_19/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"
mklink /j "fabric_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder/mp3" "mp3"

mklink /j "forge_1_19_3/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_19_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_18_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_17_1/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_16_5/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_15_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_14_4/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_12_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_8_8/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "forge_1_7_10/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_14_4/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_15_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_16_5/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_17_1/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_18_2/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_19/src/main/java/coloryr/allmusic_client/player" "player"
mklink /j "fabric_1_19_3/src/main/java/coloryr/allmusic_client/player" "player"

mklink /j "forge_1_19_3/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_19_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_18_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_17_1/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_16_5/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_15_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_14_4/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_12_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_8_8/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "forge_1_7_10/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_14_4/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_15_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_16_5/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_17_1/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_18_2/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_19/src/main/java/coloryr/allmusic_client/hud" "hud"
mklink /j "fabric_1_19_3/src/main/java/coloryr/allmusic_client/hud" "hud"

mklink /j "forge_1_19_3/build" "build"
mklink /j "forge_1_19_2/build" "build"
mklink /j "forge_1_18_2/build" "build"
mklink /j "forge_1_17_1/build" "build"
mklink /j "forge_1_16_5/build" "build"
mklink /j "forge_1_15_2/build" "build"
mklink /j "forge_1_14_4/build" "build"
mklink /j "forge_1_12_2/build" "build"
mklink /j "forge_1_8_8/build" "build"
mklink /j "forge_1_7_10/build" "build"
mklink /j "fabric_1_14_4/build" "build"
mklink /j "fabric_1_15_2/build" "build"
mklink /j "fabric_1_16_5/build" "build"
mklink /j "fabric_1_17_1/build" "build"
mklink /j "fabric_1_18_2/build" "build"
mklink /j "fabric_1_19/build" "build"
mklink /j "fabric_1_19_3/build" "build"

mklink /j "forge_1_19_3/.gradle" ".gradle"
mklink /j "forge_1_19_2/.gradle" ".gradle"
mklink /j "forge_1_18_2/.gradle" ".gradle"
mklink /j "forge_1_17_1/.gradle" ".gradle"
mklink /j "forge_1_16_5/.gradle" ".gradle"
mklink /j "forge_1_15_2/.gradle" ".gradle"
mklink /j "forge_1_14_4/.gradle" ".gradle"
mklink /j "forge_1_12_2/.gradle" ".gradle"
mklink /j "forge_1_8_8/.gradle" ".gradle"
mklink /j "forge_1_7_10/.gradle" ".gradle"
mklink /j "fabric_1_14_4/.gradle" ".gradle"
mklink /j "fabric_1_15_2/.gradle" ".gradle"
mklink /j "fabric_1_16_5/.gradle" ".gradle"
mklink /j "fabric_1_17_1/.gradle" ".gradle"
mklink /j "fabric_1_18_2/.gradle" ".gradle"
mklink /j "fabric_1_19/.gradle" ".gradle"
mklink /j "fabric_1_19_3/.gradle" ".gradle"