rmdir "forge_1_20_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_20/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_19_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_12_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_8_8/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "forge_1_7_10/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_14_4/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_15_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_16_5/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_17_1/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_18_2/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_19/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_19_3/src/main/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_19_4/src/client/resources/coloryr/allmusic_client/player/decoder/mp3"
rmdir "fabric_1_20/src/client/resources/coloryr/allmusic_client/player/decoder/mp3"

rmdir "forge_1_20_2/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_20/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_19_3/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_19_2/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_18_2/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_17_1/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_16_5/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_15_2/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_14_4/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_12_2/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_8_8/src/main/java/coloryr/allmusic_client/player"
rmdir "forge_1_7_10/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_14_4/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_15_2/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_16_5/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_17_1/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_18_2/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_19/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_19_3/src/main/java/coloryr/allmusic_client/player"
rmdir "fabric_1_19_4/src/client/java/coloryr/allmusic_client/player"
rmdir "fabric_1_20/src/client/java/coloryr/allmusic_client/player"

rmdir "forge_1_20_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_20/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_19_3/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_19_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_18_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_17_1/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_16_5/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_15_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_14_4/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_12_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_8_8/src/main/java/coloryr/allmusic_client/hud"
rmdir "forge_1_7_10/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_14_4/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_15_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_16_5/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_17_1/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_18_2/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_19/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_19_3/src/main/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_19_4/src/client/java/coloryr/allmusic_client/hud"
rmdir "fabric_1_20/src/client/java/coloryr/allmusic_client/hud"

rmdir /s /q  "forge_1_20_2/build"
rmdir /s /q  "forge_1_20/build"
rmdir /s /q  "forge_1_19_3/build"
rmdir /s /q  "forge_1_19_2/build"
rmdir /s /q  "forge_1_18_2/build"
rmdir /s /q  "forge_1_17_1/build"
rmdir /s /q  "forge_1_16_5/build"
rmdir /s /q  "forge_1_15_2/build"
rmdir /s /q  "forge_1_14_4/build"
rmdir /s /q  "forge_1_12_2/build"
rmdir /s /q  "forge_1_8_8/build"
rmdir /s /q  "forge_1_7_10/build"
rmdir /s /q  "fabric_1_14_4/build"
rmdir /s /q  "fabric_1_15_2/build"
rmdir /s /q  "fabric_1_16_5/build"
rmdir /s /q  "fabric_1_17_1/build"
rmdir /s /q  "fabric_1_18_2/build"
rmdir /s /q  "fabric_1_19/build"
rmdir /s /q  "fabric_1_19_3/build"
rmdir /s /q  "fabric_1_19_4/build"
rmdir /s /q  "fabric_1_20/build"

rmdir /s /q  "forge_1_20_2/.gradle"
rmdir /s /q  "forge_1_20/.gradle"
rmdir /s /q  "forge_1_19_3/.gradle"
rmdir /s /q  "forge_1_19_2/.gradle"
rmdir /s /q  "forge_1_18_2/.gradle"
rmdir /s /q  "forge_1_17_1/.gradle"
rmdir /s /q  "forge_1_16_5/.gradle"
rmdir /s /q  "forge_1_15_2/.gradle"
rmdir /s /q  "forge_1_14_4/.gradle"
rmdir /s /q  "forge_1_12_2/.gradle"
rmdir /s /q  "forge_1_8_8/.gradle"
rmdir /s /q  "forge_1_7_10/.gradle"
rmdir /s /q  "fabric_1_14_4/.gradle"
rmdir /s /q  "fabric_1_15_2/.gradle"
rmdir /s /q  "fabric_1_16_5/.gradle"
rmdir /s /q  "fabric_1_17_1/.gradle"
rmdir /s /q  "fabric_1_18_2/.gradle"
rmdir /s /q  "fabric_1_19/.gradle"
rmdir /s /q  "fabric_1_19_3/.gradle"
rmdir /s /q  "fabric_1_19_4/.gradle"
rmdir /s /q  "fabric_1_20/.gradle"